### ISSUE TITLE
.gitignore

### ISSUE THREAD

**Issue by benceHornyak** [smartagent47/smartagent47.github.io#1]
U should ignore 
```
.sass-cache/
*css.map
```
 because those are generated files. And only sources should be pushed to git.. u can easy remove with 
`git rm <file name>` and push it to git..
To prevent these kind of issues I usually google <lang that I'm coding> gitignore and build a .gitignore file

**Comment by theIYD** [comment]
The files have been deleted. 

Thank you for letting me know.
